packages:
  - apps/*
  - packages/*
  - configs/*
catalogs:
  react18:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - esbuild
  - lefthook
  - sharp
