import type { Grasshopper } from "../../src/entities/grasshoppers/model/grasshopper.model";

export const GRASSHOPPERS_WITH_IMAGE: Grasshopper[] = [
  { id: "1", name: "가시모메뚜기", imgSrc: "/grasshoppers/가시모메뚜기.png" },
  { id: "2", name: "각시메뚜기", imgSrc: "/grasshoppers/각시메뚜기.jpg" },
  { id: "3", name: "검정수염메뚜기", imgSrc: "/grasshoppers/검정수염메뚜기.jpg" },
  { id: "4", name: "극동벼메뚜기", imgSrc: "/grasshoppers/극동벼메뚜기.png" },
  { id: "5", name: "극동애메뚜기", imgSrc: "/grasshoppers/극동애메뚜기.png" },
  { id: "6", name: "긴날개밑들이메뚜기", imgSrc: "/grasshoppers/긴날개밑들이메뚜기.png" },
  { id: "7", name: "꼭지메뚜기", imgSrc: "/grasshoppers/꼭지메뚜기.png" },
  { id: "8", name: "끝검은메뚜기", imgSrc: "/grasshoppers/끝검은메뚜기.png" },
  { id: "9", name: "두꺼비메뚜기", imgSrc: "/grasshoppers/두꺼비메뚜기.png" },
  { id: "10", name: "등검은메뚜기", imgSrc: "/grasshoppers/등검은메뚜기.png" },
  { id: "11", name: "땅딸보메뚜기", imgSrc: "/grasshoppers/땅딸보메뚜기.png" },
  { id: "12", name: "뚱보주름메뚜기", imgSrc: "/grasshoppers/뚱보주름메뚜기.png" },
  { id: "13", name: "모메뚜기", imgSrc: "/grasshoppers/모메뚜기.png" },
  { id: "14", name: "발톱메뚜기", imgSrc: "/grasshoppers/발톱메뚜기.png" },
  { id: "15", name: "벼메뚜기붙이", imgSrc: "/grasshoppers/벼메뚜기붙이.png" },
  { id: "16", name: "섬서구메뚜기", imgSrc: "/grasshoppers/섬서구메뚜기.png" },
  { id: "17", name: "수염치레애메뚜기", imgSrc: "/grasshoppers/수염치레애메뚜기.png" },
  { id: "18", name: "시베리아애메뚜기", imgSrc: "/grasshoppers/시베리아애메뚜기.png" },
  { id: "19", name: "야산모메뚜기", imgSrc: "/grasshoppers/야산모메뚜기.png" },
  { id: "20", name: "우리벼메뚜기", imgSrc: "/grasshoppers/우리벼메뚜기.png" },
  { id: "21", name: "원산밑들이메뚜기", imgSrc: "/grasshoppers/원산밑들이메뚜기.png" },
  { id: "22", name: "장삼모메뚜기", imgSrc: "/grasshoppers/장삼모메뚜기.png" },
  { id: "23", name: "제주밑들이메뚜기", imgSrc: "/grasshoppers/제주밑들이메뚜기.png" },
  { id: "24", name: "제주청날개애메뚜기", imgSrc: "/grasshoppers/제주청날개애메뚜기.jpg" },
  { id: "25", name: "좁쌀메뚜기", imgSrc: "/grasshoppers/좁쌀메뚜기.png" },
  { id: "26", name: "참볼록모메뚜기", imgSrc: "/grasshoppers/참볼록모메뚜기.png" },
  { id: "27", name: "참홍날개메뚜기", imgSrc: "/grasshoppers/참홍날개메뚜기.jpg" },
  { id: "28", name: "청날개애메뚜기", imgSrc: "/grasshoppers/청날개애메뚜기.png" },
  { id: "29", name: "청분홍메뚜기", imgSrc: "/grasshoppers/청분홍메뚜기.png" },
  { id: "30", name: "팔공산밑들이메뚜기", imgSrc: "/grasshoppers/팔공산밑들이메뚜기.png" },
  { id: "31", name: "한국민날개밑들이메뚜기", imgSrc: "/grasshoppers/한국민날개밑들이메뚜기.png" },
  { id: "32", name: "한라북방밑들이메뚜기", imgSrc: "/grasshoppers/한라북방밑들이메뚜기.png" },
  { id: "33", name: "한라애메뚜기", imgSrc: "/grasshoppers/한라애메뚜기.jpg" },
  { id: "34", name: "해변메뚜기", imgSrc: "/grasshoppers/해변메뚜기.png" },
  { id: "35", name: "홍날개메뚜기", imgSrc: "/grasshoppers/홍날개메뚜기.jpg" },
];

export const GRASSHOPPER_WITH_NO_IMAGE: Grasshopper[] = [
  { id: "36", name: "알락방울벌레", imgSrc: "/grasshoppers/알락방울벌레.png" },
  { id: "37", name: "청솔귀뚜라미", imgSrc: "/grasshoppers/청솔귀뚜라미.png" },
  { id: "38", name: "분홍눈여치", imgSrc: "/grasshoppers/분홍눈여치.png" },
  { id: "39", name: "풀무치", imgSrc: "/grasshoppers/풀무치.png" },
  { id: "40", name: "왕땅강아지", imgSrc: "/grasshoppers/왕땅강아지.png" },
  { id: "41", name: "왕매부리", imgSrc: "/grasshoppers/왕매부리.png" },
  { id: "42", name: "여치베짱이", imgSrc: "/grasshoppers/여치베짱이.png" },
  { id: "43", name: "나뭇잎대왕베짱이", imgSrc: "/grasshoppers/나뭇잎대왕베짱이.png" },
  { id: "44", name: "백두산삽사리", imgSrc: "/grasshoppers/백두산삽사리.png" },
  { id: "45", name: "리옥크", imgSrc: "/grasshoppers/리옥크.png" },
  { id: "46", name: "먹종다리", imgSrc: "/grasshoppers/먹종다리.png" },
  { id: "47", name: "딱따기", imgSrc: "/grasshoppers/딱따기.png" },
  { id: "48", name: "땅강아지", imgSrc: "/grasshoppers/땅강아지.png" },
  { id: "49", name: "산여치", imgSrc: "/grasshoppers/산여치.png" },
  { id: "50", name: "긴꼬리쌕쌔기", imgSrc: "/grasshoppers/긴꼬리쌕쌔기.png" },
  { id: "51", name: "곰귀뚜라미", imgSrc: "/grasshoppers/곰귀뚜라미.png" },
  { id: "52", name: "뚱보귀뚜라미", imgSrc: "/grasshoppers/뚱보귀뚜라미.png" },
  { id: "53", name: "산꼽등이", imgSrc: "/grasshoppers/산꼽등이.png" },
  { id: "54", name: "굴꼽등이", imgSrc: "/grasshoppers/굴꼽등이.png" },
  { id: "55", name: "왕귀뚜라미", imgSrc: "/grasshoppers/왕귀뚜라미.png" },
  { id: "56", name: "방울벌레", imgSrc: "/grasshoppers/방울벌레.png" },
  { id: "57", name: "점박이쌕쌔기", imgSrc: "/grasshoppers/점박이쌕쌔기.png" },
  { id: "58", name: "방아깨비", imgSrc: "/grasshoppers/방아깨비.png" },
  { id: "59", name: "어리여치", imgSrc: "/grasshoppers/어리여치.png" },
  { id: "60", name: "사가 페도", imgSrc: "/grasshoppers/사가 페도.png" },
  { id: "61", name: "중베짱이", imgSrc: "/grasshoppers/중베짱이.png" },
  { id: "62", name: "꼬마여치베짱이", imgSrc: "/grasshoppers/꼬마여치베짱이.png" },
  { id: "63", name: "검은다리실베짱이", imgSrc: "/grasshoppers/검은다리실베짱이.png" },
  { id: "64", name: "우리여치", imgSrc: "/grasshoppers/우리여치.png" },
  { id: "65", name: "팥중이", imgSrc: "/grasshoppers/팥중이.png" },
  { id: "66", name: "철써기", imgSrc: "/grasshoppers/철써기.png" },
  { id: "67", name: "야산알락귀뚜라미", imgSrc: "/grasshoppers/야산알락귀뚜라미.png" },
  { id: "68", name: "쌍색여치", imgSrc: "/grasshoppers/쌍색여치.png" },
  { id: "69", name: "자이언트 웨타", imgSrc: "/grasshoppers/자이언트 웨타.png" },
  { id: "70", name: "곰방울벌레", imgSrc: "/grasshoppers/곰방울벌레.png" },
  { id: "71", name: "폭날개애메뚜기", imgSrc: "/grasshoppers/폭날개애메뚜기.png" },
  { id: "72", name: "아머드그라운드크리켓", imgSrc: "/grasshoppers/아머드그라운드크리켓.png" },
  { id: "73", name: "검정꼽등이", imgSrc: "/grasshoppers/검정꼽등이.png" },
  { id: "74", name: "콩중이", imgSrc: "/grasshoppers/콩중이.png" },
  { id: "75", name: "핀보스메뚜기", imgSrc: "/grasshoppers/핀보스메뚜기.png" },
  { id: "76", name: "애여치", imgSrc: "/grasshoppers/애여치.png" },
  { id: "77", name: "꼽등이", imgSrc: "/grasshoppers/꼽등이.png" },
  { id: "78", name: "파크타운 프런", imgSrc: "/grasshoppers/파크타운 프런.png" },
];
