import { GrasshopperType } from "../model/grasshopper.model";

export const Grasshoppers: GrasshopperType[] = [
  { id: "1", name: "가시모메뚜기", imgSrc: "/grasshoppers/가시모메뚜기.png" },
  { id: "2", name: "각시메뚜기", imgSrc: "/grasshoppers/각시메뚜기.jpg" },
  { id: "3", name: "검정수염메뚜기", imgSrc: "/grasshoppers/검정수염메뚜기.jpg" },
  { id: "4", name: "극동벼메뚜기", imgSrc: "/grasshoppers/극동벼메뚜기.png" },
  { id: "5", name: "극동애메뚜기", imgSrc: "/grasshoppers/극동애메뚜기.png" },
  { id: "6", name: "긴날개밑들이메뚜기", imgSrc: "/grasshoppers/긴날개밑들이메뚜기.png" },
  { id: "7", name: "꼭지메뚜기", imgSrc: "/grasshoppers/꼭지메뚜기.png" },
  { id: "8", name: "끝검은메뚜기", imgSrc: "/grasshoppers/끝검은메뚜기.png" },
  { id: "9", name: "두꺼비메뚜기", imgSrc: "/grasshoppers/두꺼비메뚜기.png" },
  { id: "10", name: "등검은메뚜기", imgSrc: "/grasshoppers/등검은메뚜기.png" },
  { id: "11", name: "땅딸보메뚜기", imgSrc: "/grasshoppers/땅딸보메뚜기.png" },
  { id: "12", name: "뚱보주름메뚜기", imgSrc: "/grasshoppers/뚱보주름메뚜기.png" },
  { id: "13", name: "모메뚜기", imgSrc: "/grasshoppers/모메뚜기.png" },
  { id: "14", name: "발톱메뚜기", imgSrc: "/grasshoppers/발톱메뚜기.png" },
  { id: "15", name: "벼메뚜기붙이", imgSrc: "/grasshoppers/벼메뚜기붙이.png" },
  { id: "16", name: "섬서구메뚜기", imgSrc: "/grasshoppers/섬서구메뚜기.png" },
  { id: "17", name: "수염치레애메뚜기", imgSrc: "/grasshoppers/수염치레애메뚜기.png" },
  { id: "18", name: "시베리아애메뚜기", imgSrc: "/grasshoppers/시베리아애메뚜기.png" },
  { id: "19", name: "야산모메뚜기", imgSrc: "/grasshoppers/야산모메뚜기.png" },
  { id: "20", name: "우리벼메뚜기", imgSrc: "/grasshoppers/우리벼메뚜기.png" },
  { id: "21", name: "원산밑들이메뚜기", imgSrc: "/grasshoppers/원산밑들이메뚜기.png" },
  { id: "22", name: "장삼모메뚜기", imgSrc: "/grasshoppers/장삼모메뚜기.png" },
  { id: "23", name: "제주밑들이메뚜기", imgSrc: "/grasshoppers/제주밑들이메뚜기.png" },
  { id: "24", name: "제주청날개애메뚜기", imgSrc: "/grasshoppers/제주청날개애메뚜기.jpg" },
  { id: "25", name: "좁쌀메뚜기", imgSrc: "/grasshoppers/좁쌀메뚜기.png" },
  { id: "26", name: "참볼록모메뚜기", imgSrc: "/grasshoppers/참볼록모메뚜기.png" },
  { id: "27", name: "참홍날개메뚜기", imgSrc: "/grasshoppers/참홍날개메뚜기.jpg" },
  { id: "28", name: "청날개애메뚜기", imgSrc: "/grasshoppers/청날개애메뚜기.png" },
  { id: "29", name: "청분홍메뚜기", imgSrc: "/grasshoppers/청분홍메뚜기.png" },
  { id: "30", name: "팔공산밑들이메뚜기", imgSrc: "/grasshoppers/팔공산밑들이메뚜기.png" },
  { id: "31", name: "한국민날개밑들이메뚜기", imgSrc: "/grasshoppers/한국민날개밑들이메뚜기.png" },
  { id: "32", name: "한라북방밑들이메뚜기", imgSrc: "/grasshoppers/한라북방밑들이메뚜기.png" },
  { id: "33", name: "한라애메뚜기", imgSrc: "/grasshoppers/한라애메뚜기.jpg" },
  { id: "34", name: "해변메뚜기", imgSrc: "/grasshoppers/해변메뚜기.png" },
  { id: "35", name: "홍날개메뚜기", imgSrc: "/grasshoppers/홍날개메뚜기.jpg" },
];
